import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
 en:{
   students: "students",
   student: "Student",
   teacher: 'Teacher',
   hourlyRate: 'Hourly Rate',
   classHours: 'Class Hours',
   request: 'Request',
   messages: 'Messages',
   message: 'Message',
   hour: 'hour',
   hours: 'hours',
   feed: 'Feed',
   overview: 'Overview',
   courses: 'Courses',
   account: 'Account Settings',
   name: 'Name',
   email: 'E-mail',
   password: 'Password',
   country: 'Country',
   city: 'City',
   rate: 'Rate',
   statement: 'Personal Statement',
   save: 'Save',
   accepted: 'Accepted',
   requested: 'Requested',
   accept: 'Accept',
   waiting: 'Waiting',
   start: 'Start',
   participants: 'Participants',
	 leave: 'Leave Room',
   join: 'Join Room',
   signUp: 'Sign Up',
   signIn:"Sign In",
   logout: "Sign Out",
   logIn: 'Log In',
   loading: 'Loading...',
   signInErrorOne: "User is not registered",
   signInErrorTwo: "Incorrect e-mail or password",
   acceptedNotif: 'accepted your request to connect',
   requestedNotif: 'sent you a class request',
   connectedNotifPartOne: 'You and',
   connectedNotifPartTwo: 'are now connected',
   noNotif: 'You don\'t have any notification',
   home:"Home",
   back: "Back",
   homeSentence: "Get Started",
   studyingHours: "Studying Hours",
   noStudyingHours: "You have not completed any studying hour yet",
   teachingHours: "Teaching Hours",
   noTeachingHours: "You have not completed any teaching hour yet"
 },
 zh: {
   students: "学生",
   student: "学生",
   teacher: '老师',
   hourlyRate: '每小时价格',
   classHours: '课时',
   request: '报名',
   messages: '聊天',
   message: '聊天',
   hour: '小时',
   hours: '小时',
   feed: '主页',
   overview: '概观',
   courses: '课程',
   account: '用户信息',
   name: '名字',
   email: '邮箱',
   password: '密码',
   country: '国家',
   city: '城市',
   rate: '价格',
   statement: '个人陈述',
   save: '保存',
   accepted: '接受',
   requested: '请求',
   accept: '确认',
   waiting: '等待回复中',
   start: '开始上课',
   participants: 'Participants',
	 leave: '退出教室',
   join: '进入教室',
   signUp: '注册',
   signIn:"登陆",
   logout: "退出",
   logIn: '登陆',
   loading: '加载中...',
   signInErrorOne: "用户尚未注册",
   signInErrorTwo: "邮箱或密码错误",
   acceptedNotif: '接受了您的聊天请求',
   requestedNotif: '邀请您加入一门课程',
   connectedNotifPartOne: '您和',
   connectedNotifPartTwo: '已接通',
   noNotif: '您目前没有信息',
   home:"主页",
   back: "退回",
   homeSentence: "开始",
   studyingHours: "学习课时",
   noStudyingHours: "还未完成学习课时",
   teachingHours: "教书课时",
   noTeachingHours: "你还没有完成课时"
 }
});
/**
 * Uncomment the string below to force Chinese language.
 */
//strings.setLanguage('zh');

export default strings;