import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
 en:{
   students: "students",
   student: "Student",
   teacher: 'Teacher',
   hourlyRate: 'Hourly Rate',
   classHours: 'Class Hours',
   request: 'Request',
   messages: 'Messages',
   message: 'Message',
   hour: 'hour',
   hours: 'hours',
   feed: 'Feed',
   overview: 'Overview',
   classes: 'My Classes',
   account: 'Account Settings',
   name: 'Name',
   email: 'E-mail',
   password: 'Password',
   country: 'Country',
   city: 'City',
   rate: 'Rate',
   statement: 'Personal Statement',
   save: 'Save',
   accepted: 'Accepted',
   requested: 'Requested',
   accept: 'Accept',
   waiting: 'Waiting',
   start: 'Start',
   participants: 'Participants',
	 leave: 'Leave Room',
   join: 'Join Room',
   signUp: 'Sign Up',
   signIn:"Sign In",
   logout: "Sign out",
   logIn: 'Log In',
   loading: 'Loading...',
   signInErrorOne: "User is not registered",
   signInErrorTwo: "Incorrect e-mail or password",
   acceptedNotif: 'accepted your request to connect',
   requestedNotif: 'sent you a class request',
   connectedNotifPartOne: 'You and',
   connectedNotifPartTwo: 'are now connected',
   noNotif: 'You don\'t have any notification',
   home:"Home"
 },
 zh: {
   students: "学生",
   student: "学生",
   teacher: '老师',
   hourlyRate: '价格',
   classHours: 'Class Hours',
   request: '报名',
   messages: '聊天',
   message: '聊天',
   hour: '小时',
   hours: '小时',
   feed: '主页',
   overview: 'Overview',
   classes: 'My Classes',
   account: '用户信息',
   name: '名字',
   email: '邮箱',
   password: '密码',
   country: '国家',
   city: '城市',
   rate: '价格',
   statement: 'Personal Statement',
   save: 'Save',
   accepted: 'Accepted',
   requested: 'Requested',
   accept: '确认',
   waiting: '等待回复中',
   start: '开始上课',
   participants: 'Participants',
	 leave: 'Leave Room',
   join: 'Join Room',
   signUp: '注册',
   signIn:"登陆",
   logout: "Sign out",
   logIn: '登陆',
   loading: 'Loading...',
   signInErrorOne: "User is not registered",
   signInErrorTwo: "Incorrect e-mail or password",
   acceptedNotif: 'accepted your request to connect',
   requestedNotif: 'sent you a class request',
   connectedNotifPartOne: 'You and',
   connectedNotifPartTwo: 'are now connected',
   noNotif: 'You don\'t have any notification',
   home:"Home"
 }
});
//strings.setLanguage('zh');

export default strings;